changes3

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,9 +6,8 @@ on:
       - main
 
 jobs:
-   deploy:
+  deploy:
     runs-on: ubuntu-latest
-    needs: [build]
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -26,10 +25,10 @@ jobs:
         run: |
           scp -r * root@62.72.1.215:/var/www/laravel
 
-      - name: Install Composer
+      - name: Install Composer dependencies
         run: |
           cd /var/www/laravel
-          composer install --no-dev --prefer-dist --no-interaction
+          composer install --no-dev --prefer-dist --no-interaction || { echo "Composer install failed"; exit 1; }
 
       - name: Install Node.js and npm
         uses: actions/setup-node@v2
@@ -39,7 +38,7 @@ jobs:
       - name: Install npm dependencies
         run: |
           cd /var/www/laravel
-          npm install 
+          npm install || { echo "npm install failed"; exit 1; }
 
       - name: SSH commands
         run: |
